export const SEARCH_VIDEOGAMES = 'SEARCH_VIDEOGAMES';
export const VIEW_VIDEOGAME = 'VIEW_VIDEOGAME';
export const FILTER_VIDEOGAMES = 'FILTER_VIDEOGAMES';
export const SORT_VIDEOGAMES = 'SORT_VIDEOGAMES';
export const CREATE_VIDEOGAME = 'CREATE_VIDEOGAME';
export const DELETE_VIDEOGAME = 'DELETE_VIDEOGAME';

export const FETCH_VIDEOGAMES_PAGE_REQUEST = 'FETCH_VIDEOGAMES_PAGE_REQUEST';
export const FETCH_VIDEOGAMES_PAGE_SUCCESS = 'FETCH_VIDEOGAMES_PAGE_SUCCESS';
export const FETCH_VIDEOGAMES_PAGE_FAILURE = 'FETCH_VIDEOGAMES_PAGE_FAILURE';